variables:
  PARALLEL_BUILDS: 4
  MAX_LOGICAL_PROCESSORS: 8
  CMAKE_BUILD_DRIVER: "--parallel %PARALLEL_BUILDS% -- /p:CL_MPcount=%MAX_LOGICAL_PROCESSORS%"
  GIT_SUBMODULE_STRATEGY: normal
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"

default:
  tags:
  - windows
  - amd64

stages:
  - preflight
  - build
  - smoketest
  - package
  

build_release_fidelityfx_loader_dll_dx12:
  stage: build
  script:
  - '"C:/Program Files\Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/MSBuild.exe" ./Kits/FidelityFX/api/dx12/amd_fidelityfx_loader_dx12_2022.sln /p:Configuration=Release /p:Platform=x64'
  artifacts:
    paths:
    - ./Kits/FidelityFX/bin/amd_fidelityfx_loader_dx12.dll
    - ./Kits/FidelityFX/bin/amd_fidelityfx_loader_dx12.pdb
    - ./Kits/FidelityFX/bin/amd_fidelityfx_loader_dx12.lib
    expire_in: 1 week

build_fidelityfx_sc:
  stage: build
  tags:
  - vcpkg
  script:
  - '"C:/Program Files\Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/MSBuild.exe" ./Kits/FidelityFX/tools/ffx_sc/FidelityFX_SC_vs2022.sln /p:Configuration=Release /p:Platform=x64'
  artifacts:
    paths:
    - ./Kits/FidelityFX/tools/ffx_sc/bin/dxcompiler.dll
    - ./Kits/FidelityFX/tools/ffx_sc/bin/dxil.lib
    - ./Kits/FidelityFX/tools/ffx_sc/bin/FidelityFX_SC.exe
    expire_in: 1 week  

build_release_fidelityfx_framegeneration_dll_dx12:
  stage: build
  tags:
  - vcpkg
  needs:
  - job: build_fidelityfx_sc
  script:
  - '"C:/Program Files\Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/MSBuild.exe" ./Kits/FidelityFX/framegeneration/dx12/amd_fidelityfx_framegeneration_dx12_2022.sln /p:Configuration=Release /p:Platform=x64'
  artifacts:
    paths:
    - ./Kits/FidelityFX/bin/amd_fidelityfx_framegeneration_dx12.dll
    - ./Kits/FidelityFX/bin/amd_fidelityfx_framegeneration_dx12.pdb
    - ./Kits/FidelityFX/bin/amd_fidelityfx_framegeneration_dx12.lib
    expire_in: 1 week

build_release_fidelityfx_upscaler_dll_dx12:
  stage: build
  tags:
  - vcpkg
  needs:
  - job: build_fidelityfx_sc
  script:
  - '"C:/Program Files\Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/MSBuild.exe" ./Kits/FidelityFX/upscalers/dx12/amd_fidelityfx_upscaler_dx12_2022.sln /p:Configuration=Release /p:Platform=x64'
  artifacts:
    paths:
    - ./Kits/FidelityFX/bin/amd_fidelityfx_upscaler_dx12.dll
    - ./Kits/FidelityFX/bin/amd_fidelityfx_upscaler_dx12.pdb
    - ./Kits/FidelityFX/bin/amd_fidelityfx_upscaler_dx12.lib
    expire_in: 1 week

build_release_fsr_cauldron2_dx12:
  stage: build
  tags:
  - vcpkg
  needs:
  - job: build_release_fidelityfx_loader_dll_dx12
  - job: build_release_fidelityfx_framegeneration_dll_dx12
  - job: build_release_fidelityfx_upscaler_dll_dx12
  script:
  - '"C:/Program Files\Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/MSBuild.exe" ./Samples/Upscalers/FidelityFX_FSR/dx12/FidelityFX_FSR_2022.sln /p:Configuration=Release /p:Platform=x64'
  artifacts:
    paths:
    - ./Samples/Upscalers/FidelityFX_FSR/dx12/x64/Release
    expire_in: 1 week

# Run smoke tests for SDK
test_ffx_api:
  stage: smoketest
  needs:
  - job: build_release_fidelityfx_loader_dll_dx12
  - job: build_release_fidelityfx_upscaler_dll_dx12
  dependencies:
    - build_release_fidelityfx_loader_dll_dx12
    - build_release_fidelityfx_upscaler_dll_dx12
  script:
    - 'call "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/Tools/VsDevCmd.bat" -arch=x64 -host_arch=x64'
    - 'xcopy "Kits\\FidelityFX\\bin\\amd_fidelityfx_loader_dx12.dll" "Kits\\FidelityFX\\api\\test\\"'
    - 'xcopy "Kits\\FidelityFX\\bin\\amd_fidelityfx_upscaler_dx12.dll" "Kits\\FidelityFX\\api\\test\\"'
    - 'cd Kits/FidelityFX/api/test'
    - 'runtests.bat'
  artifacts:
    when: always
    reports:
      junit: Kits/FidelityFX/api/test/ffx-api-test_abi_report.xml
      junit: Kits/FidelityFX/api/test/ffx-api-runtime_tests_report.xml
      junit: Kits/FidelityFX/api/test/ffx-api-runtime_tests_externalprovider_report.xml

test_ffx_api_dx12:
  stage: smoketest
  needs:
  - job: build_release_fidelityfx_loader_dll_dx12
  script:
    - 'call "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/Tools/VsDevCmd.bat" -arch=x64 -host_arch=x64'
    - 'cd Kits/FidelityFX/api/dx12/test'
    - 'runtests.bat'
  artifacts:
    when: always
    reports:
      junit: Kits/FidelityFX/api/dx12/test/ffx-api-test_abi_dx12_report.xml

test_ffx_api_upscale:
  stage: smoketest
  needs:
  - job: build_release_fidelityfx_loader_dll_dx12
  - job: build_release_fidelityfx_upscaler_dll_dx12
  script:
    - 'call "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/Tools/VsDevCmd.bat" -arch=x64 -host_arch=x64'
    - 'xcopy "Kits\\FidelityFX\\bin\\amd_fidelityfx_loader_dx12.dll" "Kits\\FidelityFX\\upscalers\\test\\"'
    - 'xcopy "Kits\\FidelityFX\\bin\\amd_fidelityfx_upscaler_dx12.dll" "Kits\\FidelityFX\\upscalers\\test\\"'
    - 'cd Kits/FidelityFX/upscalers/test'
    - 'runtests.bat'
  artifacts:
    when: always
    reports:
      junit: Kits/FidelityFX/upscalers/test/ffx-api-test_abi_upscale_report.xml
      junit: Kits/FidelityFX/upscalers/test/ffx-api-runtime_tests_upscale_no_ctx_report.xml

test_ffx_api_framegeneration:
  stage: smoketest
  needs:
  - job: build_release_fidelityfx_framegeneration_dll_dx12
  script:
    - 'call "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/Tools/VsDevCmd.bat" -arch=x64 -host_arch=x64'
    - 'cd Kits/FidelityFX/framegeneration/test'
    - 'runtests.bat'
  artifacts:
    when: always
    reports:
      junit: Kits/FidelityFX/framegeneration/test/ffx-api-test_abi_framegeneration_report.xml
      
test_ffx_api_framegeneration_dx12:
  stage: smoketest
  needs:
  - job: build_release_fidelityfx_framegeneration_dll_dx12
  script:
    - 'call "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/Tools/VsDevCmd.bat" -arch=x64 -host_arch=x64'
    - 'cd Kits/FidelityFX/framegeneration/dx12/test'
    - 'runtests.bat'
  artifacts:
    when: always
    reports:
      junit: Kits/FidelityFX/framegeneration/dx12/test/ffx-api-test_abi_framegeneration_dx12_report.xml

# package SDK public repo seed
package_release_sdk_samples:
  stage: package
  needs:
  - job: build_release_fidelityfx_loader_dll_dx12
  - job: build_release_fidelityfx_framegeneration_dll_dx12
  - job: build_release_fidelityfx_upscaler_dll_dx12
  - job: build_release_fsr_cauldron2_dx12
  - test_ffx_api
  - test_ffx_api_dx12
  - test_ffx_api_framegeneration
  - test_ffx_api_framegeneration_dx12
  - test_ffx_api_upscale
  script:
  - echo "Packaging FidelityFX SDK Samples"
  artifacts:
    name: "FIDELITYFX-SDK2.0-$CI_COMMIT_SHORT_SHA$"
    paths:
    - ./*.bat
    - ./readme.md
    - ./docs
    - ./Kits/Cauldron2
    - ./Kits/FidelityFX/api/include/*.*
    - ./Kits/FidelityFX/api/include/dx12
    - ./Kits/FidelityFX/api/internal/*.*
    - ./Kits/FidelityFX/api/internal/gpu
    - ./Kits/FidelityFX/backend/dx12
    - ./Kits/FidelityFX/framegeneration/fsr3/dx12
    - ./Kits/FidelityFX/framegeneration/fsr3/include
    - ./Kits/FidelityFX/framegeneration/fsr3/internal
    - ./Kits/FidelityFX/framegeneration/include/dx12
    - ./Kits/FidelityFX/framegeneration/include/*.*
    - ./Kits/FidelityFX/bin/*.dll
    - ./Kits/FidelityFX/bin/*.pdb
    - ./Kits/FidelityFX/bin/*.lib
    - ./Kits/FidelityFX/signedbin/amd_fidelityfx_loader_dx12.*
    - ./Kits/FidelityFX/signedbin/amd_fidelityfx_framegeneration_dx12.*
    - ./Kits/FidelityFX/signedbin/amd_fidelityfx_upscaler_dx12.*
    - ./Kits/FidelityFX/upscalers/fsr3/dx12
    - ./Kits/FidelityFX/upscalers/fsr3/include
    - ./Kits/FidelityFX/upscalers/fsr3/internal
    - ./Kits/FidelityFX/upscalers/include
    - ./Kits/OpenSource/imgui
    - ./Kits/OpenSource/nlohmann
    - ./Kits/OpenSource/stb
    - ./Kits/OpenSource/vectormath
    - ./Samples/Upscalers/FidelityFX_FSR/dx12/*.*
    - ./Samples/Upscalers/FidelityFX_FSR/dx12/config
    - ./Samples/Upscalers/FidelityFX_FSR/dx12/resources
    - ./Tools
    expire_in: 1 week
    exclude:
    - ./Kits/FidelityFX/api/internal/ffx_api_loader.cpp
    - ./Kits/FidelityFX/api/internal/ffx_watermark.*
    - ./Kits/FidelityFX/api/internal/git_hash_branch.h
    - ./Kits/FidelityFX/api/internal/make_git_info_header.bat
    - ./Kits/FidelityFX/api/internal/gpu/ffx_shader_writer.h
    - ./Kits/FidelityFX/api/internal/gpu/ffx_shader_writer_letter_macro_end.h
    - ./Kits/FidelityFX/api/internal/gpu/ffx_shader_writer_letter_macro_start.h
    - ./Kits/FidelityFX/api/internal/gpu/ffx_shader_writer_templated.h
    - ./Kits/FidelityFX/api/internal/gpu/ffx_watermark.hlsl
